name: Python Avatar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Avatar [${{ matrix.shard }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [
           1/4,  2/4,  3/4,  4/4,
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[avatar,pandora]
      - name: Rootcanal
        run: nohup python -m rootcanal > rootcanal.log &
      - name: Test
        run: |
          avatar --list | grep -Ev '^=' > test-names.txt
          timeout 5m avatar --test-beds bumble.bumbles --tests $(split test-names.txt -n l/${{ matrix.shard }})
      - name: Rootcanal Logs
        if: always()
        run: cat rootcanal.log
      - name: Upload Mobly logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mobly-logs
          path: /tmp/logs/mobly/bumble.bumbles/
